openapi: 3.0.3
info:
  title: FDX Core Transactions Mapper API
  version: 1.0.0
  description: >
    A mock FDX Core `/accounts/{accountId}/transactions` endpoint that accepts
    `offSet` and `limit` query parameters and maps them to a pageNum/pageSize backend.

servers:
  - url: http://localhost:5000

paths:
  /accounts/{accountId}/transactions:
    get:
      summary: Get paginated transaction data for an account
      description: |
        Returns a list of transactions with pagination metadata.
        Accepts `offSet` (item offset) and `limit` (items per page) query parameters.
      parameters:
        - name: accountId
          in: path
          required: true
          description: The account ID
          schema:
            type: string
            example: "33333"

        - name: offSet
          in: query
          description: Offset of the first item (zero-based index)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0

        - name: limit
          in: query
          description: Maximum number of items to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 250
            default: 10

      responses:
        '200':
          description: Paginated list of transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: object
                    properties:
                      nextOffset:
                        type: string
                        nullable: true
                        example: "10"
                      total:
                        type: integer
                        example: 1000
                  links:
                    type: object
                    properties:
                      next:
                        type: object
                        properties:
                          href:
                            type: string
                            example: "/accounts/33333/transactions?offSet=10&limit=10"
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 101
                        name:
                          type: string
                          example: "Item 101"

        '401':
          description: Unauthorized (missing or invalid API key)

        '500':
          description: Server error (upstream failure)

      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
